### ISSUE TITLE
get_min_times() fails with TypeError: '<' not supported between instances of 'list' and 'collections.OrderedDict'

### ISSUE THREAD

**Issue by rjpearce** [markgdev/OctopusAgile#15]
Hi Mark, 

Thanks for creating this module but I'm having a bit of trouble trying to use get_min_times()

The readme says: 
"Requirements a list of dicts with details of particular times that must be includes in the returned date_rate dict."

But when I try that I get an error:
  File "/Users/x/Library/Python/3.7/lib/python/site-packages/OctopusAgile/Agile.py", line 39, in get_min_times
    min_key = min(d, key=d.get)
TypeError: '<' not supported between instances of 'list' and 'collections.OrderedDict'

Below is the example code I am using
`
from OctopusAgile import Agile
from pprint import pprint
from datetime import datetime, timedelta
from collections import OrderedDict

EAST_ENGLAND='A'

agile = Agile(EAST_ENGLAND)
time_from = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
time_to = (datetime.utcnow() + timedelta(hours = 24)).strftime("%Y-%m-%dT%H:%M:%SZ")
print(time_from, time_to)

rates = agile.get_rates(time_from,  time_to)
reqs = [{"slots": 10, "time_from": time_from, "time_to": time_to}]
res = agile.get_min_times(1, rates, reqs)`
`

Can you give me a pointer as to what I am doing wrong or if this is a bug?

**Comment by rjpearce** [comment]
Sorry bit of an id10t error. If I pass the correct date_rates 

`res = agile.get_min_times(2, rates['date_rates'], reqs)`

I now get: 
Traceback (most recent call last):
  File "examples/octopus_agile_set_program.py", line 19, in <module>
    res = agile.get_min_times(2, rates['date_rates'], reqs)
  File "/Users/x/Library/Python/3.7/lib/python/site-packages/OctopusAgile/Agile.py", line 57, in get_min_times
    remove_list = self.get_max_times(min_slots - len(slots_filled), ret_d)
  File "/Users/x/Library/Python/3.7/lib/python/site-packages/OctopusAgile/Agile.py", line 69, in get_max_times
    min_key = max(d, key=d.get)
ValueError: max() arg is an empty sequence

**Comment by rjpearce** [comment]
Resolved it myself. 
After re-reading the documentation i worked it out. 
It's hard to mentally distinguish number of time periods in in_d and number of slots in time period
